{% set name = "dask-expr" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_expr-{{ version }}.tar.gz
  sha256: e6d5a7bdff927aa4a1754a76cad79c5925254c525f568038df7832fcd558fc11

build:
  number: 0
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - dask-core >=2025.1.0

test:
  imports:
    - dask_expr
  requires:
    - pip
  commands:
    - pip check

#Note: The build and dependency order for dask-distributed packages are as follows.
#      dask-core ---> dask-expr --->distributed --->dask

about:
  home: https://github.com/dask/dask-expr
  summary: High Level Expressions for Dask
  description: |
    High Level Expressions for Dask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://github.com/dask/dask-expr/blob/main/README.md
  dev_url: https://github.com/dask/dask-expr

extra:
  recipe-maintainers:
    - fjetter
    - phofl
    - jrbourbeau
