{% set name = "dask-expr" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_expr-{{ version }}.tar.gz
  sha256: cd0e0ad4d65229a4fd22a231fa9c7e632cef09c5b6ab7259bdaaaadd20179cdb

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - tomli
    - versioneer =0.28
    - wheel
  run:
    - python
    - dask-core ==2024.5.0
    - pyarrow >=7.0.0
    - pandas >=2

test:
  imports:
    - dask_expr
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/dask-expr
  summary: High Level Expressions for Dask
  description: |
    High Level Expressions for Dask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://github.com/dask/dask-expr/blob/main/README.md
  dev_url: https://github.com/dask/dask-expr

extra:
  recipe-maintainers:
    - fjetter
    - phofl
    - jrbourbeau
